### ISSUE TITLE
v.reduce is not a function

### ISSUE THREAD

**Issue by JohnLou** [laoqiren/mlhelper#5]
Error caught in uncaughtException event: TypeError: v.reduce is not a function
    at/quan-c2/node_modules/mlhelper/lib/utils/matrix/index.js:144:29
    at Array.map (<anonymous>)
    at Matrix.calAvg (/quan-c2/node_modules/mlhelper/lib/utils/matrix/index.js:143:24)
    at Object.standardScaler (/quan-c2/node_modules/mlhelper/lib/utils/features/preprocessing.js:12:28)

---
When i call:
let dataSet = [37860,8265,1828,5547,34550,1569,6381,1675,
948,844,1757,9306,1250,1516,1413,388,3164,1721,4671,
3387,1277,1179,1480,1969,1426,5973,1604,11301,3377,
1168,1009,2478,120086,1491,15668,1133,6476,1037,12578,
2060,1389,12229,1163,1726,2665,3354,2468,1775,3400,
3569,2295,1314,2979,4489,1348,9610,1126,2739,6239,6121,
3872,4469,37497,18354,26387,19950,3899,2261,8517,2222,
1036,1098,2382,1481,3869,3067,2008,1207,6031,20708,1431,
2881,6101,1114,1043,2302,8365,2532,3046,1308,1270,2559,
3389,14135,1326,1862,1246,1100,2387,1017];

let testStandardScaler = preprocessing.standardScaler(dataSet);

**Comment by JohnLou** [comment]
Multi features dataset is ok.
